=== rsugio/demoechoadapter/src/main/resources/log-configuration.dtd
<!ENTITY % severities "(NONE|FATAL|ERROR|WARNING|INFO|PATH|DEBUG|ALL)">
<!ENTITY % association-types "(PRIVATE_LOG|LOCAL_LOG|LOG)">
<!ENTITY % boolean "(TRUE | FALSE)">

<!ELEMENT log-configuration (log-formatters?, log-destinations?, log-controllers?)>

<!ELEMENT log-formatters          (log-formatter*)>
<!ELEMENT log-destinations        (log-destination*)>
<!ELEMENT log-controllers         (log-controller*)>
<!ELEMENT log-filters             (log-filter*)>
<!ELEMENT associated-destinations ((destination-ref|anonymous-destination)*)>

<!ELEMENT log-formatter     EMPTY>
<!ATTLIST log-formatter     name CDATA      #REQUIRED>
<!ATTLIST log-formatter     type NMTOKEN    #REQUIRED>
<!ATTLIST log-formatter     pattern CDATA   #IMPLIED>

<!ELEMENT log-destination   ((formatter-ref|anonymous-formatter)?, log-filters?)>
<!ATTLIST log-destination   name ID         #REQUIRED>
<!ATTLIST log-destination   type NMTOKEN    #REQUIRED>
<!ATTLIST log-destination   pattern CDATA   #IMPLIED>
<!ATTLIST log-destination   effective-severity %severities; #IMPLIED>
<!ATTLIST log-destination   encoding CDATA  #IMPLIED>
<!ATTLIST log-destination   count CDATA     #IMPLIED>
<!ATTLIST log-destination   limit CDATA     #IMPLIED>

<!ELEMENT formatter-ref     EMPTY>
<!ATTLIST formatter-ref     name CDATA #REQUIRED>

<!ELEMENT anonymous-formatter     EMPTY>
<!ATTLIST anonymous-formatter     type NMTOKEN #REQUIRED>

<!ELEMENT log-controller  (relative-severity*, associated-destinations?, log-filters?)>
<!ATTLIST log-controller  name                      CDATA #REQUIRED>
<!ATTLIST log-controller  effective-severity %severities; #IMPLIED>
<!ATTLIST log-controller  minimum-severity   %severities; #IMPLIED>
<!ATTLIST log-controller  maximum-severity   %severities; #IMPLIED>
<!ATTLIST log-controller  bundle-name               CDATA #IMPLIED>
<!ATTLIST log-controller  db-log                %boolean; #IMPLIED>

<!ELEMENT relative-severity  EMPTY>
<!ATTLIST relative-severity  relative-controller  CDATA #REQUIRED>
<!ATTLIST relative-severity  value         %severities; #IMPLIED>
<!ATTLIST relative-severity  minimum-value %severities; #IMPLIED>
<!ATTLIST relative-severity  maximum-value %severities; #IMPLIED>

<!ELEMENT log-filter        EMPTY>
<!ATTLIST log-filter        type NMTOKEN #REQUIRED>

<!ELEMENT destination-ref   EMPTY>
<!ATTLIST destination-ref   name IDREF #REQUIRED>
<!ATTLIST destination-ref   association-type %association-types; #REQUIRED>

<!ELEMENT anonymous-destination   EMPTY>
<!ATTLIST anonymous-destination   type NMTOKEN #REQUIRED>
<!ATTLIST anonymous-destination   association-type %association-types; #REQUIRED>

=== rsugio/demoechoadapter/src/main/resources/log-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log-configuration SYSTEM "log-configuration.dtd">
<log-configuration>

	<log-formatters>
		<!-- This formatter produces human readable messages. -->
		<log-formatter name="trc" pattern="%26d %150l [%t] %10s: %m" type="TraceFormatter"/>
	</log-formatters>
	
	<log-destinations>
		<!-- Destination for Trace Information of this ra demo.echoadapter.ra -->
		<log-destination count="5" effective-severity="DEBUG" limit="2000000" name="demo_echoadapter_ra.trc"
			pattern="./log/applications/demo.echoadapter.ra/default.trc" type="FileLog">
			<formatter-ref name="trc"/>
		</log-destination>
	</log-destinations>

	<log-controllers>
		<!-- Trace Location demo.echoadapter.ra -->
		<log-controller name="demo.echoadapter.ra" effective-severity="ERROR">
			<associated-destinations>
				<destination-ref association-type="LOG" name="demo_echoadapter_ra.trc"/>
			</associated-destinations>
		</log-controller>
		<!-- Logging Category: none, we use the default XILog -->
	</log-controllers>

</log-configuration>
